# This script is intended for WordPress plugins that provide hooks,
# that can be used by other plugins.
# By parsing its source code, it creates a documentation in a GitHub wiki (style).

name: Extract WordPress Hooks into /docs

on:
  push:
    branches: [ develop ]
    paths: [ '**.php' ]
  workflow_dispatch:

jobs:
  extract-hooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: akirk/extract-wp-hooks@main