# This script is intended for WordPress plugins that provide hooks,
# that can be used by other plugins.
# By parsing its source code, it creates a documentation in a GitHub wiki (style).

name: Extract WordPress Hooks into /docs

on:
  push:
    branches: [ main ]
    paths: [ '**.php' ]
  workflow_dispatch:

jobs:
  extract-hooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - uses: akirk/extract-wp-hooks@main
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        # phpstan requires PHP 7.1+.
        php-version: 7.4
        extensions: dom, iconv, json, libxml, zip
        coverage: none

    - name: Composer Install
      run: composer install --optimize-autoloader --prefer-dist

    - name: Log debug information
      run: |
        git --version
        php --version
        composer --version

    - name: Running extract-wp-hooks
      if: ${{ success() || failure() }}
      run: |
        vendor/bin/extract-wp-hooks.php